# -*- mode: ruby -*-
# vi: set ft=ruby :
vmram=1024
vmcpu = 1
Vagrant.configure("2") do |config|
  # configure Load balancer  machine
  config.vm.define "lb" do |lb|
    lb.vm.box = "fasmat/ubuntu2004-desktop"
    lb.vm.network "private_network", type: "dhcp"
    lb.vm.hostname ="Load_balancer"
  end
  config.vm.provider "virtualbox" do |v|
    v.name = "Load_balancer"
    v.memory = vmram
    v.cpus = vmcpu
  end
  python.vm.provision :shell do |shell|
    shell.path = "install_docker.yml"
  end

    # # configure Docker  machine
    # config.vm.define "docker" do |d|
    #   lb.vm.box = "ubuntu/xenial64"
    #   lb.vm.network "private_network", type:"dhcp"
    #   lb.vm.hostname ="docker"
    # end
    # config.vm.provider "virtualbox" do |v|
    #   v.name = "docker"
    #   v.memory = vmram
    #   v.cpus = vmcpu
    # end
  #   # configure first web machine
  # config.vm.define "web1" do |web1|
  #   web1.vm.box = "ubuntu/xenial64"
  #   web1.vm.network "private_network", ip: "10.0.0.11"
  # end
  # config.vm.provider "virtualbox" do |v|
  #   #v.name = "web1-VM"
  #   v.memory = vmram
  #   v.cpus = vmcpu
  # end
  #   # configure first web machine
  # config.vm.define "web2" do |web2|
  #   web2.vm.box = "ubuntu/xenial64"
  #   web2.vm.network "private_network", ip: "10.0.0.12"
  # end
  # config.vm.provider "virtualbox" do |v|
  #   #v.name = "web2-VM"
  #   v.memory = vmram
  #   v.cpus = vmcpu
  # end
end
